"""MCP server exposing Radarr's v3 REST API (OpenAPI 3.0.4) as tools.

One tool per endpoint, generated from the vendored spec at
tests/data/radarr_openapi.json (develop HEAD c6fef4309de3ffdd5e0e9607ad30beb12d791333).
Full coverage: every JSON-producing endpoint under /api/v3 plus GET /ping
(binary/text endpoints - media covers and raw log files - are excluded).

Auth is the X-Api-Key header, generated in Radarr > Settings > General >
Security. GET endpoints are marked readOnlyHint=True; POST/PUT writes are
readOnlyHint=False; DELETE endpoints additionally set destructiveHint=True so
clients can warn before calling them. Bodies are passed as opaque dicts/lists.

Tools are built at import time from the `_TOOL_REGISTRY` table below: one
async closure per entry, registered through FastMCP's Tool.from_function. The
registry is generated from the spec; keep it in sync with the vendored file
(see AGENTS.md). build_client points at the origin with no path suffix so
httpx joins the fully-qualified paths (including /ping) correctly.
"""

import os
import sys
from typing import Any
from urllib.parse import quote

import httpx
from fastmcp import FastMCP
from fastmcp.exceptions import ToolError
from fastmcp.tools import Tool
from mcp.types import ToolAnnotations

READONLY = ToolAnnotations(readOnlyHint=True)
WRITE = ToolAnnotations(readOnlyHint=False, destructiveHint=False)
DESTRUCTIVE = ToolAnnotations(readOnlyHint=False, destructiveHint=True)

# Radarr responses are plain JSON. `dict[str, Any]` (not bare `Any`) matters
# here: FastMCP needs a concrete schema to build MCP structured content, and
# skips that step entirely for an `Any` return type -- which silently makes
# Client.call_tool's `.data` come back None for any tool returning a JSON array
# (radarr_list_movie and friends). Verified against fastmcp 3.4.7.
JSONObj = dict[str, Any]
JSONVal = JSONObj | list[Any]

mcp = FastMCP("radarr-mcp")

_client: httpx.AsyncClient | None = None


def build_client(
    base_url: str, api_key: str | None, transport: httpx.BaseTransport | None = None
) -> httpx.AsyncClient:
    """Client pinned to the origin (no path suffix) so registered full paths
    like /api/v3/movie and /ping both resolve correctly via httpx base join."""
    headers = {"X-Api-Key": api_key} if api_key else {}
    return httpx.AsyncClient(base_url=f"{base_url.rstrip('/')}", headers=headers, transport=transport)


async def _req(
    method: str,
    path: str,
    params: dict[str, Any] | None = None,
    json_body: JSONVal | None = None,
) -> JSONVal:
    assert _client is not None, "client not configured"
    r = await _client.request(method, path, params=params, json=json_body)
    if r.status_code >= 400:
        try:
            msg = r.json().get("message", r.text)
        except ValueError:
            msg = r.text
        raise ToolError(f"Radarr API {r.status_code}: {msg}")
    if not r.text:
        return {}
    return r.json()


def _omit(params: dict[str, Any]) -> dict[str, Any]:
    """Drop keys whose values are empty/None so the API's defaults apply."""
    return {k: v for k, v in params.items() if v not in ("", None)}


_TOOL_REGISTRY: list[dict[str, Any]] = [{'name': 'radarr_list_alttitle',
  'method': 'GET',
  'path': '/api/v3/alttitle',
  'pp': [],
  'qp': [{'name': 'movie_id', 'wire': 'movieId', 'type': 'int', 'default': 'None'},
         {'name': 'movie_metadata_id', 'wire': 'movieMetadataId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List alternative movie titles. Query params: movie_id, movie_metadata_id.'},
 {'name': 'radarr_get_alttitle',
  'method': 'GET',
  'path': '/api/v3/alttitle/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single alternative movie titles by id.'},
 {'name': 'radarr_create_autotagging',
  'method': 'POST',
  'path': '/api/v3/autotagging',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create auto tagging rules. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_list_autotagging',
  'method': 'GET',
  'path': '/api/v3/autotagging',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List auto tagging rules.'},
 {'name': 'radarr_get_autotagging_schema',
  'method': 'GET',
  'path': '/api/v3/autotagging/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the auto tagging rules schema (available fields/options).'},
 {'name': 'radarr_update_autotagging',
  'method': 'PUT',
  'path': '/api/v3/autotagging/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update auto tagging rules. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_autotagging',
  'method': 'DELETE',
  'path': '/api/v3/autotagging/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete auto tagging rules. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_autotagging',
  'method': 'GET',
  'path': '/api/v3/autotagging/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single auto tagging rules by id.'},
 {'name': 'radarr_list_blocklist',
  'method': 'GET',
  'path': '/api/v3/blocklist',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
         {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
         {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
         {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
         {'name': 'movie_ids', 'wire': 'movieIds', 'type': 'list[Any]', 'default': 'None'},
         {'name': 'protocols', 'wire': 'protocols', 'type': 'list[Any]', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List blocklisted releases. Query params: sort_key, sort_direction, movie_ids, protocols.'},
 {'name': 'radarr_bulk_delete_blocklist',
  'method': 'DELETE',
  'path': '/api/v3/blocklist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete blocklisted releases. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_list_blocklist_movie',
  'method': 'GET',
  'path': '/api/v3/blocklist/movie',
  'pp': [],
  'qp': [{'name': 'movie_id', 'wire': 'movieId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List movies. Query params: movie_id.'},
 {'name': 'radarr_delete_blocklist',
  'method': 'DELETE',
  'path': '/api/v3/blocklist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete blocklisted releases. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_list_calendar',
  'method': 'GET',
  'path': '/api/v3/calendar',
  'pp': [],
  'qp': [{'name': 'start', 'wire': 'start', 'type': 'str', 'default': '""'},
         {'name': 'end', 'wire': 'end', 'type': 'str', 'default': '""'},
         {'name': 'unmonitored', 'wire': 'unmonitored', 'type': 'bool', 'default': 'False'},
         {'name': 'tags', 'wire': 'tags', 'type': 'str', 'default': '""'}],
  'bk': 'none',
  'doc': 'List upcoming release calendar. Query params: start, end, tags.'},
 {'name': 'radarr_list_collection',
  'method': 'GET',
  'path': '/api/v3/collection',
  'pp': [],
  'qp': [{'name': 'tmdb_id', 'wire': 'tmdbId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List movie collections. Query params: tmdb_id.'},
 {'name': 'radarr_update_collections',
  'method': 'PUT',
  'path': '/api/v3/collection',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update movie collections. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_update_collection',
  'method': 'PUT',
  'path': '/api/v3/collection/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update movie collections. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_collection',
  'method': 'GET',
  'path': '/api/v3/collection/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single movie collections by id.'},
 {'name': 'radarr_run_command',
  'method': 'POST',
  'path': '/api/v3/command',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run a Radarr command (body is a CommandResource with a `name`, e.g. RefreshMovie, MoviesSearch, '
         'DownloadedMoviesScan). WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_list_command',
  'method': 'GET',
  'path': '/api/v3/command',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List queued/running commands.'},
 {'name': 'radarr_delete_command',
  'method': 'DELETE',
  'path': '/api/v3/command/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete queued/running commands. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_command',
  'method': 'GET',
  'path': '/api/v3/command/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single queued/running commands by id.'},
 {'name': 'radarr_get_config_downloadclient',
  'method': 'GET',
  'path': '/api/v3/config/downloadclient',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List downloadclient.'},
 {'name': 'radarr_update_config_downloadclient',
  'method': 'PUT',
  'path': '/api/v3/config/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update downloadclient. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_config_downloadclient_by_id',
  'method': 'GET',
  'path': '/api/v3/config/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single downloadclient by id.'},
 {'name': 'radarr_get_config_host',
  'method': 'GET',
  'path': '/api/v3/config/host',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List host.'},
 {'name': 'radarr_update_config_host',
  'method': 'PUT',
  'path': '/api/v3/config/host/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update host. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_config_host_by_id',
  'method': 'GET',
  'path': '/api/v3/config/host/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single host by id.'},
 {'name': 'radarr_get_config_importlist',
  'method': 'GET',
  'path': '/api/v3/config/importlist',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List import lists.'},
 {'name': 'radarr_update_config_importlist',
  'method': 'PUT',
  'path': '/api/v3/config/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update import lists. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_config_importlist_by_id',
  'method': 'GET',
  'path': '/api/v3/config/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single import lists by id.'},
 {'name': 'radarr_get_config_indexer',
  'method': 'GET',
  'path': '/api/v3/config/indexer',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List indexers.'},
 {'name': 'radarr_update_config_indexer',
  'method': 'PUT',
  'path': '/api/v3/config/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update indexers. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_config_indexer_by_id',
  'method': 'GET',
  'path': '/api/v3/config/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single indexers by id.'},
 {'name': 'radarr_get_config_mediamanagement',
  'method': 'GET',
  'path': '/api/v3/config/mediamanagement',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List mediamanagement.'},
 {'name': 'radarr_update_config_mediamanagement',
  'method': 'PUT',
  'path': '/api/v3/config/mediamanagement/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update mediamanagement. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_config_mediamanagement_by_id',
  'method': 'GET',
  'path': '/api/v3/config/mediamanagement/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single mediamanagement by id.'},
 {'name': 'radarr_get_config_metadata',
  'method': 'GET',
  'path': '/api/v3/config/metadata',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List metadata providers.'},
 {'name': 'radarr_update_config_metadata',
  'method': 'PUT',
  'path': '/api/v3/config/metadata/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update metadata providers. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_config_metadata_by_id',
  'method': 'GET',
  'path': '/api/v3/config/metadata/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single metadata providers by id.'},
 {'name': 'radarr_get_config_naming',
  'method': 'GET',
  'path': '/api/v3/config/naming',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List naming.'},
 {'name': 'radarr_list_config_naming_examples',
  'method': 'GET',
  'path': '/api/v3/config/naming/examples',
  'pp': [],
  'qp': [{'name': 'rename_movies', 'wire': 'renameMovies', 'type': 'bool', 'default': 'None'},
         {'name': 'replace_illegal_characters', 'wire': 'replaceIllegalCharacters', 'type': 'bool', 'default': 'None'},
         {'name': 'colon_replacement_format', 'wire': 'colonReplacementFormat', 'type': 'str', 'default': '""'},
         {'name': 'standard_movie_format', 'wire': 'standardMovieFormat', 'type': 'str', 'default': '""'},
         {'name': 'movie_folder_format', 'wire': 'movieFolderFormat', 'type': 'str', 'default': '""'},
         {'name': 'id', 'wire': 'id', 'type': 'int', 'default': 'None'},
         {'name': 'resource_name', 'wire': 'resourceName', 'type': 'str', 'default': '""'}],
  'bk': 'none',
  'doc': 'List examples. Query params: rename_movies, replace_illegal_characters, colon_replacement_format, '
         'standard_movie_format, movie_folder_format, id, resource_name.'},
 {'name': 'radarr_update_config_naming',
  'method': 'PUT',
  'path': '/api/v3/config/naming/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update naming. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_config_naming_by_id',
  'method': 'GET',
  'path': '/api/v3/config/naming/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single naming by id.'},
 {'name': 'radarr_get_config_ui',
  'method': 'GET',
  'path': '/api/v3/config/ui',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List ui.'},
 {'name': 'radarr_update_config_ui',
  'method': 'PUT',
  'path': '/api/v3/config/ui/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update ui. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_config_ui_by_id',
  'method': 'GET',
  'path': '/api/v3/config/ui/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single ui by id.'},
 {'name': 'radarr_list_credit',
  'method': 'GET',
  'path': '/api/v3/credit',
  'pp': [],
  'qp': [{'name': 'movie_id', 'wire': 'movieId', 'type': 'int', 'default': 'None'},
         {'name': 'movie_metadata_id', 'wire': 'movieMetadataId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List movie credits (cast/crew). Query params: movie_id, movie_metadata_id.'},
 {'name': 'radarr_get_credit',
  'method': 'GET',
  'path': '/api/v3/credit/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single movie credits (cast/crew) by id.'},
 {'name': 'radarr_list_customfilter',
  'method': 'GET',
  'path': '/api/v3/customfilter',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List custom filters.'},
 {'name': 'radarr_create_customfilter',
  'method': 'POST',
  'path': '/api/v3/customfilter',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create custom filters. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_update_customfilter',
  'method': 'PUT',
  'path': '/api/v3/customfilter/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update custom filters. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_customfilter',
  'method': 'DELETE',
  'path': '/api/v3/customfilter/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete custom filters. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_customfilter',
  'method': 'GET',
  'path': '/api/v3/customfilter/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single custom filters by id.'},
 {'name': 'radarr_list_customformat',
  'method': 'GET',
  'path': '/api/v3/customformat',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List custom formats.'},
 {'name': 'radarr_create_customformat',
  'method': 'POST',
  'path': '/api/v3/customformat',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create custom formats. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_update_customformat',
  'method': 'PUT',
  'path': '/api/v3/customformat/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update custom formats. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_delete_customformat',
  'method': 'DELETE',
  'path': '/api/v3/customformat/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete custom formats. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_customformat_schema',
  'method': 'GET',
  'path': '/api/v3/customformat/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the custom formats schema (available fields/options).'},
 {'name': 'radarr_update_customformat',
  'method': 'PUT',
  'path': '/api/v3/customformat/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update custom formats. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_customformat',
  'method': 'DELETE',
  'path': '/api/v3/customformat/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete custom formats. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_customformat',
  'method': 'GET',
  'path': '/api/v3/customformat/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single custom formats by id.'},
 {'name': 'radarr_create_delayprofile',
  'method': 'POST',
  'path': '/api/v3/delayprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create delay profiles. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_list_delayprofile',
  'method': 'GET',
  'path': '/api/v3/delayprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List delay profiles.'},
 {'name': 'radarr_reorder_delayprofile',
  'method': 'PUT',
  'path': '/api/v3/delayprofile/reorder/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'after', 'wire': 'after', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Reorder delay profiles after another entry. Query params: after. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_delayprofile',
  'method': 'DELETE',
  'path': '/api/v3/delayprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete delay profiles. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_update_delayprofile',
  'method': 'PUT',
  'path': '/api/v3/delayprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update delay profiles. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_delayprofile',
  'method': 'GET',
  'path': '/api/v3/delayprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single delay profiles by id.'},
 {'name': 'radarr_get_diskspace',
  'method': 'GET',
  'path': '/api/v3/diskspace',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List diskspace.'},
 {'name': 'radarr_list_downloadclient',
  'method': 'GET',
  'path': '/api/v3/downloadclient',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List downloadclient.'},
 {'name': 'radarr_create_downloadclient',
  'method': 'POST',
  'path': '/api/v3/downloadclient',
  'pp': [],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Create downloadclient. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_action_downloadclient',
  'method': 'POST',
  'path': '/api/v3/downloadclient/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run an action on a action (name selects the action). WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_update_downloadclient',
  'method': 'PUT',
  'path': '/api/v3/downloadclient/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update downloadclient. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_delete_downloadclient',
  'method': 'DELETE',
  'path': '/api/v3/downloadclient/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete downloadclient. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_downloadclient_schema',
  'method': 'GET',
  'path': '/api/v3/downloadclient/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the downloadclient schema (available fields/options).'},
 {'name': 'radarr_test_downloadclient',
  'method': 'POST',
  'path': '/api/v3/downloadclient/test',
  'pp': [],
  'qp': [{'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Test test (optionally force_test). Returns validation results. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_test_all_downloadclient',
  'method': 'POST',
  'path': '/api/v3/downloadclient/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Test testall (optionally force_test). Returns validation results. WRITE: this modifies your Radarr '
         'instance.'},
 {'name': 'radarr_update_downloadclient',
  'method': 'PUT',
  'path': '/api/v3/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update downloadclient. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_downloadclient',
  'method': 'DELETE',
  'path': '/api/v3/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete downloadclient. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_downloadclient',
  'method': 'GET',
  'path': '/api/v3/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single downloadclient by id.'},
 {'name': 'radarr_list_exclusions',
  'method': 'GET',
  'path': '/api/v3/exclusions',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List import list exclusions.'},
 {'name': 'radarr_create_exclusions',
  'method': 'POST',
  'path': '/api/v3/exclusions',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create import list exclusions. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_create_exclusions',
  'method': 'POST',
  'path': '/api/v3/exclusions/bulk',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Create multiple import list exclusions. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_delete_exclusions',
  'method': 'DELETE',
  'path': '/api/v3/exclusions/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete import list exclusions. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_list_exclusions_paged',
  'method': 'GET',
  'path': '/api/v3/exclusions/paged',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
         {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
         {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
         {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'}],
  'bk': 'none',
  'doc': 'List import list exclusions. Query params: sort_key, sort_direction.'},
 {'name': 'radarr_update_exclusions',
  'method': 'PUT',
  'path': '/api/v3/exclusions/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update import list exclusions. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_exclusions',
  'method': 'DELETE',
  'path': '/api/v3/exclusions/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete import list exclusions. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_exclusions',
  'method': 'GET',
  'path': '/api/v3/exclusions/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single import list exclusions by id.'},
 {'name': 'radarr_list_extrafile',
  'method': 'GET',
  'path': '/api/v3/extrafile',
  'pp': [],
  'qp': [{'name': 'movie_id', 'wire': 'movieId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List extrafile. Query params: movie_id.'},
 {'name': 'radarr_list_filesystem',
  'method': 'GET',
  'path': '/api/v3/filesystem',
  'pp': [],
  'qp': [{'name': 'path', 'wire': 'path', 'type': 'str', 'default': '""'},
         {'name': 'include_files', 'wire': 'includeFiles', 'type': 'bool', 'default': 'False'},
         {'name': 'allow_folders_without_trailing_slashes',
          'wire': 'allowFoldersWithoutTrailingSlashes',
          'type': 'bool',
          'default': 'False'}],
  'bk': 'none',
  'doc': 'List server filesystem. Query params: path.'},
 {'name': 'radarr_list_filesystem_mediafiles',
  'method': 'GET',
  'path': '/api/v3/filesystem/mediafiles',
  'pp': [],
  'qp': [{'name': 'path', 'wire': 'path', 'type': 'str', 'default': '""'}],
  'bk': 'none',
  'doc': 'List mediafiles. Query params: path.'},
 {'name': 'radarr_list_filesystem_type',
  'method': 'GET',
  'path': '/api/v3/filesystem/type',
  'pp': [],
  'qp': [{'name': 'path', 'wire': 'path', 'type': 'str', 'default': '""'}],
  'bk': 'none',
  'doc': 'List type. Query params: path.'},
 {'name': 'radarr_get_health',
  'method': 'GET',
  'path': '/api/v3/health',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List health.'},
 {'name': 'radarr_list_history',
  'method': 'GET',
  'path': '/api/v3/history',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
         {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
         {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
         {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
         {'name': 'include_movie', 'wire': 'includeMovie', 'type': 'bool', 'default': 'None'},
         {'name': 'event_type', 'wire': 'eventType', 'type': 'list[Any]', 'default': 'None'},
         {'name': 'download_id', 'wire': 'downloadId', 'type': 'str', 'default': '""'},
         {'name': 'movie_ids', 'wire': 'movieIds', 'type': 'list[Any]', 'default': 'None'},
         {'name': 'languages', 'wire': 'languages', 'type': 'list[Any]', 'default': 'None'},
         {'name': 'quality', 'wire': 'quality', 'type': 'list[Any]', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List download/import history. Query params: sort_key, sort_direction, include_movie, event_type, '
         'download_id, movie_ids, languages, quality.'},
 {'name': 'radarr_mark_history_item_failed',
  'method': 'POST',
  'path': '/api/v3/history/failed/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Mark a history item as failed (blocklists the release by default). WRITE: this modifies your Radarr '
         'instance.'},
 {'name': 'radarr_list_history_movie',
  'method': 'GET',
  'path': '/api/v3/history/movie',
  'pp': [],
  'qp': [{'name': 'movie_id', 'wire': 'movieId', 'type': 'int', 'default': 'None'},
         {'name': 'event_type', 'wire': 'eventType', 'type': 'str', 'default': '""'},
         {'name': 'include_movie', 'wire': 'includeMovie', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'List movies. Query params: movie_id, event_type.'},
 {'name': 'radarr_list_history_since',
  'method': 'GET',
  'path': '/api/v3/history/since',
  'pp': [],
  'qp': [{'name': 'date', 'wire': 'date', 'type': 'str', 'default': '""'},
         {'name': 'event_type', 'wire': 'eventType', 'type': 'str', 'default': '""'},
         {'name': 'include_movie', 'wire': 'includeMovie', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'List since. Query params: date, event_type.'},
 {'name': 'radarr_list_importlist',
  'method': 'GET',
  'path': '/api/v3/importlist',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List import lists.'},
 {'name': 'radarr_create_importlist',
  'method': 'POST',
  'path': '/api/v3/importlist',
  'pp': [],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Create import lists. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_action_importlist',
  'method': 'POST',
  'path': '/api/v3/importlist/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run an action on a action (name selects the action). WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_update_importlist',
  'method': 'PUT',
  'path': '/api/v3/importlist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update import lists. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_delete_importlist',
  'method': 'DELETE',
  'path': '/api/v3/importlist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete import lists. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_list_importlist_movie',
  'method': 'GET',
  'path': '/api/v3/importlist/movie',
  'pp': [],
  'qp': [{'name': 'include_recommendations', 'wire': 'includeRecommendations', 'type': 'bool', 'default': 'False'},
         {'name': 'include_trending', 'wire': 'includeTrending', 'type': 'bool', 'default': 'False'},
         {'name': 'include_popular', 'wire': 'includePopular', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'List movies.'},
 {'name': 'radarr_import_list_movie',
  'method': 'POST',
  'path': '/api/v3/importlist/movie',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Import movies from an import list. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_importlist_schema',
  'method': 'GET',
  'path': '/api/v3/importlist/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the import lists schema (available fields/options).'},
 {'name': 'radarr_test_importlist',
  'method': 'POST',
  'path': '/api/v3/importlist/test',
  'pp': [],
  'qp': [{'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Test test (optionally force_test). Returns validation results. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_test_all_importlist',
  'method': 'POST',
  'path': '/api/v3/importlist/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Test testall (optionally force_test). Returns validation results. WRITE: this modifies your Radarr '
         'instance.'},
 {'name': 'radarr_update_importlist',
  'method': 'PUT',
  'path': '/api/v3/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update import lists. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_importlist',
  'method': 'DELETE',
  'path': '/api/v3/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete import lists. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_importlist',
  'method': 'GET',
  'path': '/api/v3/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single import lists by id.'},
 {'name': 'radarr_list_indexer',
  'method': 'GET',
  'path': '/api/v3/indexer',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List indexers.'},
 {'name': 'radarr_create_indexer',
  'method': 'POST',
  'path': '/api/v3/indexer',
  'pp': [],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Create indexers. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_action_indexer',
  'method': 'POST',
  'path': '/api/v3/indexer/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run an action on a action (name selects the action). WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_update_indexer',
  'method': 'PUT',
  'path': '/api/v3/indexer/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update indexers. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_delete_indexer',
  'method': 'DELETE',
  'path': '/api/v3/indexer/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete indexers. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_indexer_schema',
  'method': 'GET',
  'path': '/api/v3/indexer/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the indexers schema (available fields/options).'},
 {'name': 'radarr_test_indexer',
  'method': 'POST',
  'path': '/api/v3/indexer/test',
  'pp': [],
  'qp': [{'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Test test (optionally force_test). Returns validation results. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_test_all_indexer',
  'method': 'POST',
  'path': '/api/v3/indexer/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Test testall (optionally force_test). Returns validation results. WRITE: this modifies your Radarr '
         'instance.'},
 {'name': 'radarr_update_indexer',
  'method': 'PUT',
  'path': '/api/v3/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update indexers. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_indexer',
  'method': 'DELETE',
  'path': '/api/v3/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete indexers. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_indexer',
  'method': 'GET',
  'path': '/api/v3/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single indexers by id.'},
 {'name': 'radarr_get_indexerflag',
  'method': 'GET',
  'path': '/api/v3/indexerflag',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List indexer flags.'},
 {'name': 'radarr_list_language',
  'method': 'GET',
  'path': '/api/v3/language',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List languages.'},
 {'name': 'radarr_get_language',
  'method': 'GET',
  'path': '/api/v3/language/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single languages by id.'},
 {'name': 'radarr_list_localization',
  'method': 'GET',
  'path': '/api/v3/localization',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List localization strings.'},
 {'name': 'radarr_get_localization_language',
  'method': 'GET',
  'path': '/api/v3/localization/language',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List languages.'},
 {'name': 'radarr_list_log',
  'method': 'GET',
  'path': '/api/v3/log',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
         {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
         {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
         {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
         {'name': 'level', 'wire': 'level', 'type': 'str', 'default': '""'}],
  'bk': 'none',
  'doc': 'List server logs. Query params: sort_key, sort_direction, level.'},
 {'name': 'radarr_list_log_file',
  'method': 'GET',
  'path': '/api/v3/log/file',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List file.'},
 {'name': 'radarr_list_log_file_update',
  'method': 'GET',
  'path': '/api/v3/log/file/update',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List file log files.'},
 {'name': 'radarr_list_manualimport',
  'method': 'GET',
  'path': '/api/v3/manualimport',
  'pp': [],
  'qp': [{'name': 'folder', 'wire': 'folder', 'type': 'str', 'default': '""'},
         {'name': 'download_id', 'wire': 'downloadId', 'type': 'str', 'default': '""'},
         {'name': 'movie_id', 'wire': 'movieId', 'type': 'int', 'default': 'None'},
         {'name': 'filter_existing_files', 'wire': 'filterExistingFiles', 'type': 'bool', 'default': 'True'}],
  'bk': 'none',
  'doc': 'List manual import candidates. Query params: folder, download_id, movie_id.'},
 {'name': 'radarr_commit_manual_import',
  'method': 'POST',
  'path': '/api/v3/manualimport',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Commit a manual import (body is a list of manual import items). WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_list_metadata',
  'method': 'GET',
  'path': '/api/v3/metadata',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List metadata providers.'},
 {'name': 'radarr_create_metadata',
  'method': 'POST',
  'path': '/api/v3/metadata',
  'pp': [],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Create metadata providers. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_action_metadata',
  'method': 'POST',
  'path': '/api/v3/metadata/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run an action on a action (name selects the action). WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_metadata_schema',
  'method': 'GET',
  'path': '/api/v3/metadata/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the metadata providers schema (available fields/options).'},
 {'name': 'radarr_test_metadata',
  'method': 'POST',
  'path': '/api/v3/metadata/test',
  'pp': [],
  'qp': [{'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Test test (optionally force_test). Returns validation results. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_test_all_metadata',
  'method': 'POST',
  'path': '/api/v3/metadata/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Test testall (optionally force_test). Returns validation results. WRITE: this modifies your Radarr '
         'instance.'},
 {'name': 'radarr_update_metadata',
  'method': 'PUT',
  'path': '/api/v3/metadata/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update metadata providers. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_metadata',
  'method': 'DELETE',
  'path': '/api/v3/metadata/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete metadata providers. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_metadata',
  'method': 'GET',
  'path': '/api/v3/metadata/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single metadata providers by id.'},
 {'name': 'radarr_list_movie',
  'method': 'GET',
  'path': '/api/v3/movie',
  'pp': [],
  'qp': [{'name': 'tmdb_id', 'wire': 'tmdbId', 'type': 'int', 'default': 'None'},
         {'name': 'exclude_local_covers', 'wire': 'excludeLocalCovers', 'type': 'bool', 'default': 'False'},
         {'name': 'language_id', 'wire': 'languageId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List movies. Query params: tmdb_id, language_id.'},
 {'name': 'radarr_add_movie',
  'method': 'POST',
  'path': '/api/v3/movie',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Add a movie to Radarr (body is a MovieResource). WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_update_movie',
  'method': 'PUT',
  'path': '/api/v3/movie/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update movies. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_delete_movie',
  'method': 'DELETE',
  'path': '/api/v3/movie/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete movies. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_import_movie',
  'method': 'POST',
  'path': '/api/v3/movie/import',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Import movies (body is a list of movie resources). WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_lookup_movie',
  'method': 'GET',
  'path': '/api/v3/movie/lookup',
  'pp': [],
  'qp': [{'name': 'term', 'wire': 'term', 'type': 'str', 'default': '""'}],
  'bk': 'none',
  'doc': 'List lookup. Query params: term.'},
 {'name': 'radarr_lookup_movie_by_imdb_id',
  'method': 'GET',
  'path': '/api/v3/movie/lookup/imdb',
  'pp': [],
  'qp': [{'name': 'imdb_id', 'wire': 'imdbId', 'type': 'str', 'default': '""'}],
  'bk': 'none',
  'doc': 'List imdb matching a search term. Query params: imdb_id.'},
 {'name': 'radarr_lookup_movie_by_tmdb_id',
  'method': 'GET',
  'path': '/api/v3/movie/lookup/tmdb',
  'pp': [],
  'qp': [{'name': 'tmdb_id', 'wire': 'tmdbId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List tmdb matching a search term. Query params: tmdb_id.'},
 {'name': 'radarr_update_movie',
  'method': 'PUT',
  'path': '/api/v3/movie/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [{'name': 'move_files', 'wire': 'moveFiles', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update movies. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_movie',
  'method': 'DELETE',
  'path': '/api/v3/movie/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'delete_files', 'wire': 'deleteFiles', 'type': 'bool', 'default': 'False'},
         {'name': 'add_import_exclusion', 'wire': 'addImportExclusion', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'Delete movies. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_movie',
  'method': 'GET',
  'path': '/api/v3/movie/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single movies by id.'},
 {'name': 'radarr_get_movie_folder',
  'method': 'GET',
  'path': '/api/v3/movie/{id}/folder',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single folder by id.'},
 {'name': 'radarr_list_moviefile',
  'method': 'GET',
  'path': '/api/v3/moviefile',
  'pp': [],
  'qp': [{'name': 'movie_id', 'wire': 'movieId', 'type': 'list[Any]', 'default': 'None'},
         {'name': 'movie_file_ids', 'wire': 'movieFileIds', 'type': 'list[Any]', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List movie files. Query params: movie_id, movie_file_ids.'},
 {'name': 'radarr_bulk_delete_moviefile',
  'method': 'DELETE',
  'path': '/api/v3/moviefile/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete movie files. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_bulk_update_moviefile',
  'method': 'PUT',
  'path': '/api/v3/moviefile/bulk',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Bulk update movie files. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_bulk_edit_moviefiles',
  'method': 'PUT',
  'path': '/api/v3/moviefile/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update movie files. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_update_moviefile',
  'method': 'PUT',
  'path': '/api/v3/moviefile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update movie files. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_moviefile',
  'method': 'DELETE',
  'path': '/api/v3/moviefile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete movie files. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_moviefile',
  'method': 'GET',
  'path': '/api/v3/moviefile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single movie files by id.'},
 {'name': 'radarr_list_notification',
  'method': 'GET',
  'path': '/api/v3/notification',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List notification providers.'},
 {'name': 'radarr_create_notification',
  'method': 'POST',
  'path': '/api/v3/notification',
  'pp': [],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Create notification providers. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_action_notification',
  'method': 'POST',
  'path': '/api/v3/notification/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run an action on a action (name selects the action). WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_notification_schema',
  'method': 'GET',
  'path': '/api/v3/notification/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the notification providers schema (available fields/options).'},
 {'name': 'radarr_test_notification',
  'method': 'POST',
  'path': '/api/v3/notification/test',
  'pp': [],
  'qp': [{'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Test test (optionally force_test). Returns validation results. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_test_all_notification',
  'method': 'POST',
  'path': '/api/v3/notification/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Test testall (optionally force_test). Returns validation results. WRITE: this modifies your Radarr '
         'instance.'},
 {'name': 'radarr_update_notification',
  'method': 'PUT',
  'path': '/api/v3/notification/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update notification providers. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_notification',
  'method': 'DELETE',
  'path': '/api/v3/notification/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete notification providers. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_notification',
  'method': 'GET',
  'path': '/api/v3/notification/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single notification providers by id.'},
 {'name': 'radarr_get_parse',
  'method': 'GET',
  'path': '/api/v3/parse',
  'pp': [],
  'qp': [{'name': 'title', 'wire': 'title', 'type': 'str', 'default': '""'}],
  'bk': 'none',
  'doc': 'List title parsing results. Query params: title.'},
 {'name': 'radarr_list_qualitydefinition',
  'method': 'GET',
  'path': '/api/v3/qualitydefinition',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List quality definitions.'},
 {'name': 'radarr_get_qualitydefinition_limits',
  'method': 'GET',
  'path': '/api/v3/qualitydefinition/limits',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List quality definitions.'},
 {'name': 'radarr_update_quality_definitions',
  'method': 'PUT',
  'path': '/api/v3/qualitydefinition/update',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Update quality definitions. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_update_qualitydefinition',
  'method': 'PUT',
  'path': '/api/v3/qualitydefinition/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update quality definitions. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_qualitydefinition',
  'method': 'GET',
  'path': '/api/v3/qualitydefinition/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single quality definitions by id.'},
 {'name': 'radarr_create_qualityprofile',
  'method': 'POST',
  'path': '/api/v3/qualityprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create quality profiles. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_list_qualityprofile',
  'method': 'GET',
  'path': '/api/v3/qualityprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List quality profiles.'},
 {'name': 'radarr_get_qualityprofile_schema',
  'method': 'GET',
  'path': '/api/v3/qualityprofile/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the quality profiles schema (available fields/options).'},
 {'name': 'radarr_delete_qualityprofile',
  'method': 'DELETE',
  'path': '/api/v3/qualityprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete quality profiles. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_update_qualityprofile',
  'method': 'PUT',
  'path': '/api/v3/qualityprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update quality profiles. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_qualityprofile',
  'method': 'GET',
  'path': '/api/v3/qualityprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single quality profiles by id.'},
 {'name': 'radarr_list_queue',
  'method': 'GET',
  'path': '/api/v3/queue',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
         {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
         {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
         {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
         {'name': 'include_unknown_movie_items',
          'wire': 'includeUnknownMovieItems',
          'type': 'bool',
          'default': 'False'},
         {'name': 'include_movie', 'wire': 'includeMovie', 'type': 'bool', 'default': 'False'},
         {'name': 'movie_ids', 'wire': 'movieIds', 'type': 'list[Any]', 'default': 'None'},
         {'name': 'protocol', 'wire': 'protocol', 'type': 'str', 'default': '""'},
         {'name': 'languages', 'wire': 'languages', 'type': 'list[Any]', 'default': 'None'},
         {'name': 'quality', 'wire': 'quality', 'type': 'list[Any]', 'default': 'None'},
         {'name': 'status', 'wire': 'status', 'type': 'list[Any]', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List download client queue items. Query params: sort_key, sort_direction, movie_ids, protocol, languages, '
         'quality, status.'},
 {'name': 'radarr_bulk_delete_queue',
  'method': 'DELETE',
  'path': '/api/v3/queue/bulk',
  'pp': [],
  'qp': [{'name': 'remove_from_client', 'wire': 'removeFromClient', 'type': 'bool', 'default': 'True'},
         {'name': 'blocklist', 'wire': 'blocklist', 'type': 'bool', 'default': 'False'},
         {'name': 'skip_redownload', 'wire': 'skipRedownload', 'type': 'bool', 'default': 'False'},
         {'name': 'change_category', 'wire': 'changeCategory', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Bulk delete download client queue items. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_queue_details',
  'method': 'GET',
  'path': '/api/v3/queue/details',
  'pp': [],
  'qp': [{'name': 'movie_id', 'wire': 'movieId', 'type': 'int', 'default': 'None'},
         {'name': 'include_movie', 'wire': 'includeMovie', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'List download client queue items. Query params: movie_id.'},
 {'name': 'radarr_grab_queue_bulk',
  'method': 'POST',
  'path': '/api/v3/queue/grab/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Grab the queued item now (forces the download client to fetch it). WRITE: this modifies your Radarr '
         'instance.'},
 {'name': 'radarr_grab_queue_item',
  'method': 'POST',
  'path': '/api/v3/queue/grab/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Grab the queued item now (forces the download client to fetch it). WRITE: this modifies your Radarr '
         'instance.'},
 {'name': 'radarr_get_queue_status',
  'method': 'GET',
  'path': '/api/v3/queue/status',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List download client queue items.'},
 {'name': 'radarr_delete_queue',
  'method': 'DELETE',
  'path': '/api/v3/queue/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'remove_from_client', 'wire': 'removeFromClient', 'type': 'bool', 'default': 'True'},
         {'name': 'blocklist', 'wire': 'blocklist', 'type': 'bool', 'default': 'False'},
         {'name': 'skip_redownload', 'wire': 'skipRedownload', 'type': 'bool', 'default': 'False'},
         {'name': 'change_category', 'wire': 'changeCategory', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'Delete download client queue items. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_search_releases',
  'method': 'POST',
  'path': '/api/v3/release',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Search for releases for a movie (body carries movieId and other options). WRITE: this modifies your Radarr '
         'instance.'},
 {'name': 'radarr_list_release',
  'method': 'GET',
  'path': '/api/v3/release',
  'pp': [],
  'qp': [{'name': 'movie_id', 'wire': 'movieId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List release search results. Query params: movie_id.'},
 {'name': 'radarr_push_release',
  'method': 'POST',
  'path': '/api/v3/release/push',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Push a release to the download client. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_create_releaseprofile',
  'method': 'POST',
  'path': '/api/v3/releaseprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create release profiles. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_list_releaseprofile',
  'method': 'GET',
  'path': '/api/v3/releaseprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List release profiles.'},
 {'name': 'radarr_delete_releaseprofile',
  'method': 'DELETE',
  'path': '/api/v3/releaseprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete release profiles. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_update_releaseprofile',
  'method': 'PUT',
  'path': '/api/v3/releaseprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update release profiles. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_releaseprofile',
  'method': 'GET',
  'path': '/api/v3/releaseprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single release profiles by id.'},
 {'name': 'radarr_create_remotepathmapping',
  'method': 'POST',
  'path': '/api/v3/remotepathmapping',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create remote path mappings. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_list_remotepathmapping',
  'method': 'GET',
  'path': '/api/v3/remotepathmapping',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List remote path mappings.'},
 {'name': 'radarr_delete_remotepathmapping',
  'method': 'DELETE',
  'path': '/api/v3/remotepathmapping/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete remote path mappings. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_update_remotepathmapping',
  'method': 'PUT',
  'path': '/api/v3/remotepathmapping/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update remote path mappings. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_remotepathmapping',
  'method': 'GET',
  'path': '/api/v3/remotepathmapping/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single remote path mappings by id.'},
 {'name': 'radarr_get_rename',
  'method': 'GET',
  'path': '/api/v3/rename',
  'pp': [],
  'qp': [{'name': 'movie_id', 'wire': 'movieId', 'type': 'list[Any]', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List rename. Query params: movie_id.'},
 {'name': 'radarr_create_rootfolder',
  'method': 'POST',
  'path': '/api/v3/rootfolder',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create root folders. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_list_rootfolder',
  'method': 'GET',
  'path': '/api/v3/rootfolder',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List root folders.'},
 {'name': 'radarr_delete_rootfolder',
  'method': 'DELETE',
  'path': '/api/v3/rootfolder/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete root folders. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_rootfolder',
  'method': 'GET',
  'path': '/api/v3/rootfolder/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single root folders by id.'},
 {'name': 'radarr_list_system_backup',
  'method': 'GET',
  'path': '/api/v3/system/backup',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List backup.'},
 {'name': 'radarr_restore_backup_upload',
  'method': 'POST',
  'path': '/api/v3/system/backup/restore/upload',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Restore Radarr from an uploaded backup file (multipart upload - limited support). WRITE: this modifies your '
         'Radarr instance.'},
 {'name': 'radarr_restore_backup',
  'method': 'POST',
  'path': '/api/v3/system/backup/restore/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Restore Radarr from a backup. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_system_backup',
  'method': 'DELETE',
  'path': '/api/v3/system/backup/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete backup. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_restart_radarr',
  'method': 'POST',
  'path': '/api/v3/system/restart',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Restart the Radarr service. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_system_routes',
  'method': 'GET',
  'path': '/api/v3/system/routes',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List routes.'},
 {'name': 'radarr_get_system_routes_duplicate',
  'method': 'GET',
  'path': '/api/v3/system/routes/duplicate',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List duplicate registered API routes.'},
 {'name': 'radarr_shutdown_radarr',
  'method': 'POST',
  'path': '/api/v3/system/shutdown',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Shut down the Radarr service. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_get_system_status',
  'method': 'GET',
  'path': '/api/v3/system/status',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List system.'},
 {'name': 'radarr_get_system_task',
  'method': 'GET',
  'path': '/api/v3/system/task',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List task.'},
 {'name': 'radarr_get_system_task_by_id',
  'method': 'GET',
  'path': '/api/v3/system/task/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single task by id.'},
 {'name': 'radarr_list_tag',
  'method': 'GET',
  'path': '/api/v3/tag',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List tags.'},
 {'name': 'radarr_create_tag',
  'method': 'POST',
  'path': '/api/v3/tag',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create tags. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_list_tag_detail',
  'method': 'GET',
  'path': '/api/v3/tag/detail',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List detail.'},
 {'name': 'radarr_get_tag_detail',
  'method': 'GET',
  'path': '/api/v3/tag/detail/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single detail by id.'},
 {'name': 'radarr_update_tag',
  'method': 'PUT',
  'path': '/api/v3/tag/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update tags. WRITE: this modifies your Radarr instance.'},
 {'name': 'radarr_delete_tag',
  'method': 'DELETE',
  'path': '/api/v3/tag/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete tags. DESTRUCTIVE: this deletes data.'},
 {'name': 'radarr_get_tag',
  'method': 'GET',
  'path': '/api/v3/tag/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single tags by id.'},
 {'name': 'radarr_list_update',
  'method': 'GET',
  'path': '/api/v3/update',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List available updates.'},
 {'name': 'radarr_list_wanted_cutoff',
  'method': 'GET',
  'path': '/api/v3/wanted/cutoff',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
         {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
         {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
         {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
         {'name': 'monitored', 'wire': 'monitored', 'type': 'bool', 'default': 'True'}],
  'bk': 'none',
  'doc': 'List cutoff. Query params: sort_key, sort_direction.'},
 {'name': 'radarr_list_wanted_missing',
  'method': 'GET',
  'path': '/api/v3/wanted/missing',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
         {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
         {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
         {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
         {'name': 'monitored', 'wire': 'monitored', 'type': 'bool', 'default': 'True'}],
  'bk': 'none',
  'doc': 'List missing. Query params: sort_key, sort_direction.'},
 {'name': 'radarr_ping',
  'method': 'GET',
  'path': '/ping',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Ping the server to verify it is reachable and authenticated.'}]



def _tool_source(spec: dict[str, Any]) -> str:
    parts: list[str] = []
    for p in spec["pp"]:
        parts.append(f"{p['name']}: {p['type']}")
    for q in spec["qp"]:
        parts.append(f"{q['name']}: {q['type']} = {q['default']}")
    if spec["bk"] == "dict":
        parts.append("body: dict[str, Any] = {}")
    elif spec["bk"] == "list":
        parts.append("body: list[Any] = []")
    sig = ", ".join(parts)

    path_tmpl = spec["path"]
    for p in spec["pp"]:
        path_tmpl = path_tmpl.replace("{" + p["wire"] + "}", "{" + p["name"] + "}")
    if spec["pp"]:
        arg_call = ", ".join(f"{p['name']}=quote(str({p['name']}))" for p in spec["pp"])
        url_expr = f'f"{path_tmpl}".format({arg_call})'
    else:
        url_expr = repr(spec["path"])

    if spec["qp"]:
        params_expr = "_omit({" + ", ".join(f'"{q["wire"]}": {q["name"]}' for q in spec["qp"]) + "})"
    else:
        params_expr = "None"
    json_expr = "body" if spec["bk"] != "none" else "None"

    doc = spec["doc"].replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return (
        f"async def {spec['name']}({sig}) -> JSONVal:\n"
        f'    """{doc}"""\n'
        f"    return await _req({spec['method']!r}, {url_expr}, params={params_expr}, json_body={json_expr})\n"
    )


def register_tools() -> None:
    src = "\n".join(_tool_source(spec) for spec in _TOOL_REGISTRY)
    ns: dict[str, Any] = {}
    exec(src, globals(), ns)
    for spec in _TOOL_REGISTRY:
        fn = ns[spec["name"]]
        if spec["method"] == "GET":
            ann = READONLY
        elif spec["method"] == "DELETE":
            ann = DESTRUCTIVE
        else:
            ann = WRITE
        mcp.add_tool(Tool.from_function(fn, name=spec["name"], description=spec["doc"], annotations=ann))


register_tools()


def main() -> None:
    global _client
    url = os.environ.get("RADARR_URL")
    if not url:
        print("RADARR_URL environment variable is required (e.g. http://radarr.example.com)", file=sys.stderr)
        raise SystemExit(1)
    _client = build_client(url, os.environ.get("RADARR_API_KEY"))
    mcp.run()


if __name__ == "__main__":
    main()
